### ISSUE TITLE
Combining rotate and scale on hover does not seem to work

### ISSUE THREAD

**Issue by rowild** [benface/tailwindcss-transforms#14]
I have classes like these:

```
scale-100 hover:scale-110 rotate-180 hover:rotate-90
```

If I remove the `hover: rotate-90`, the scale works, if I leave it, it does not.
But: Having no rotate class on hover makes the item spin back to its original rotation state.

Is that intended behaviour or a bug?

**Comment by benface** [comment]
@rowild Unfortunately, since all those utilities set the same `transform` property, they cannot be combined. It doesn't have anything to do with `hover`, in fact just the following doesn't work:

```
scale-110 rotate-90
```

That is, an element with these two classes won't be scaled AND rotated at the same time. It will be one or the other, depending on which utility appears last in the CSS. That is a limitation of CSS that the plugin doesn't really do anything to work around. I considered automatically generating "combined" selectors like this:

```css
.scale-110.rotate-90 {
  transform: scale(1.1) rotate(90deg);
}
```

But doing that for every single combination would result in a crazy amount of CSS, and we'd also have to deal with specificity issues. It doesn't seem like a realistic solution.

You can always add your own custom combined transform utilities like this:

```js
// tailwind.config.js
{
  theme: {
    transform: {
      'none': 'none',
      'scale-110-and-rotate-90': 'scale(1.1) rotate(90deg)',
    },
  },
  variants: {
    transform: ['hover', 'responsive'],
  },
}
```

And use them like this:

```
rotate-180 hover:transform-scale-110-and-rotate-90
```

Granted, that's pretty ugly... what I usually do instead is apply the utilities I want to combine to different wrapper elements, like this:

```html
<div class="scale-100 hover:scale-110">
  <div class="rotate-180 hover:rotate-90">...</div>
</div>
```

That way, the `rotate` utilities don't override the `scale` ones, and the end result is the same.

Note that a real solution to this CSS problem is being planned in the [CSS Transforms Level 2 spec](https://drafts.csswg.org/css-transforms-2/#individual-transforms), with individual `translate`, `scale`, and `rotate` properties. It will be a while before browsers support that, but when they do, I will definitely add support for them in this plugin. :)

**Comment by rowild** [comment]
Wow! That's a fantastic answer! Thank yo so much!!!
I actually did apply rotate and scale to parent and child element right after I posted this issue. So thanks for confirming that solution, too!

Great stuff you are doing here! Congrats!
